### ISSUE TITLE
running error on Calab 

### ISSUE THREAD

**Issue by smazrouee** [niemasd/FAVITES#6] opened 2018-03-13 16:16 UTC
Sounds like problem with docker deamon or sth
## Configuration File

{
"ContactNetwork": "NetworkX",
"ContactNetworkGenerator": "RandomPartitionGraph",
"d_or_u": "u",

"rpg_p_in": 0.004,
"rpg_p_out": 0.0002,
"rpg_sizes": [1000,1000,1000,1000,1000],
"end_time": 10,
"num_seeds": 50,
"out_dir": "/Users/sepideh/FAVITES/output/set1/output_1_1",

"Driver": "Default",
"EndCriteria": "GEMF",
"Logging": "File",

"NodeAvailability": "Bernoulli",
"node_sample_prob": 0.1,
"NumBranchSample": "Single",
"NumTimeSample": "Once",
"SourceSample": "Random",
"TimeSample": "GranichFirstART",

"NodeEvolution": "VirusTreeSimulator",
"vts_growthRate": 2.851904,
"vts_model": "logistic",
"vts_n0": 1,
"vts_t50": -2,

"PostValidation": "Dummy",

"SeedSelection": "Random",

"SeedSequence": "VirusPureCoalescentGTRGamma",
"viral_sequence_type": "HIV1-B-DNA-POL-LITTLE",

"SequenceEvolution": "GTRGammaSeqGen",
"Sequencing": "Perfect",

"TransmissionNodeSample": "GEMF",
"hiv_a1_to_d": 0,
"hiv_a2_to_a3": 0,
"hiv_a2_to_d": 0,
"hiv_a1_to_i1": 0.48,
"hiv_a2_to_i2": 0.48,
"hiv_i2_to_a2": 0.5,
"hiv_i1_to_a1": 0.5,
"hiv_a3_to_a4": 0,
"hiv_a3_to_d": 0,
"hiv_a3_to_i3": 0,
"hiv_a4_to_d": 0,
"hiv_a4_to_i4": 0,
"hiv_i1_to_d": 0,
"hiv_i1_to_i2": 8.666666666666666,
"hiv_a1_to_a2": 4.33333,
"hiv_i2_to_d": 0,
"hiv_i2_to_i3": 0,
"hiv_i3_to_a3": 0,
"hiv_i3_to_d": 0,
"hiv_i3_to_i4": 0,
"hiv_i4_to_a4": 0,
"hiv_i4_to_d": 0,
"hiv_ns_to_d": 0,
"hiv_ns_to_s": 999999,
"hiv_s_to_d": 0,
"hiv_s_to_i1_by_a1": 0.005625,
"hiv_s_to_i1_by_a2": 0,
"hiv_s_to_i1_by_a3": 0,
"hiv_s_to_i1_by_a4": 0,
"hiv_s_to_i1_by_i1": 0.1125,
"hiv_s_to_i1_by_i2": 0.1,
"hiv_s_to_i1_by_i3": 0,
"hiv_s_to_i1_by_i4": 0,
"hiv_s_to_i1_seed": 0,
"TransmissionTimeSample": "HIVARTGranichGEMF",

"TreeNode": "Simple",
"TreeUnit": "LogNormal",
"tree_rate_mean": -6.164,
"tree_rate_stdev": 0.3,

"grinder_path": "grinder",
"gemf_path": "GEMF",
"hmmemit_path": "hmmemit",
"java_path": "java",
"nw_rename_path": "nw_rename",
"seqgen_path": "seq-gen",

"seed_population": 20,

"seqgen_a_to_c": 1.765707,
"seqgen_a_to_g": 9.587649,
"seqgen_a_to_t": 0.691915,
"seqgen_c_to_g": 0.863348,
"seqgen_c_to_t": 10.282617,
"seqgen_freq_a": 0.392,
"seqgen_freq_c": 0.165,
"seqgen_freq_g": 0.212,
"seqgen_freq_t": 0.232,
"seqgen_g_to_t": 1.0,
"seqgen_gamma_shape": 0.405129,
"seqgen_num_gamma_rate_categories": ""

}

## Unexpected Behavior

run_favites_docker.py -c CONFIG1-1.json 
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.35/images/json: dial unix /var/run/docker.sock: connect: permission denied
Traceback (most recent call last):
  File "/calab_data/mirarab/home//sepideh/.bin/run_favites_docker.py", line 31, in <module>
    o = check_output(['docker','images']).decode().splitlines()
  File "/usr/lib/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['docker', 'images']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/calab_data/mirarab/home//sepideh/.bin/run_favites_docker.py", line 36, in <module>
    raise RuntimeError("docker images command failed\n%s"%e.output)
RuntimeError: docker images command failed
b''

**Comment by niemasd** [comment] 2018-03-13 16:24
The issue is your output directory. You're specifying a directory that's in root. You should specify output directories you have write access to

**Comment by niemasd** [comment] 2018-03-13 16:35
Actually, looking at this, your error was when my script tried to run the `docker images` command, which is strange because I just ran it fine right now

**Comment by niemasd** [comment] 2018-03-13 23:58
I'm able to consistently run `docker images` and whatnot on Calab, so I'm going to close this

**Closed by niemasd** 2018-03-13 23:58 UTC

**Comment by smazrouee** [comment] 2018-03-14 03:24
Update for future references: the problem is resolved for my user today,
when Calab admin granted my user credentials to run docker without sudo
access (sudo usermod -a -G docker [username]). Before then I was
getting RuntimeError:
docker images command failed.

Let's not rush to closing an issue before it's fixed for other users. Your
username is good for testing but probably not the best indication of
resolving the problem if you don't see any errors.
